config/routes.rb
Rails.application.routes.draw do

  scope module: 'customers' do
    resource :customers, except: :create
    resources :items
    get '/genreitem/:id' => 'items#genreitem', as: 'genreitems'
    resources :orders do
      collection do
        post :confirm
        get :complete

      end
    end
    resources :cart_items do

    collection do
    delete 'destroy_all', to: 'cart_items#destroy_all'
    end

    end

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    get '/customers/withdraw_confirm' => 'customers#withdraw_confirm'
    patch '/customers/withdraw' => 'customers#withdraw'

  end


   devise_for :admins,skip: [:passwords], controllers: {
  sessions: "admins/sessions"
}
    namespace :admins do
    resources :items
    resources :customers
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:index, :update, :show] do
      resources :order_items, only: [:update]
    end
    get '/' => 'homes#top'

  end

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "customers/registrations",
    sessions: 'customers/sessions'
}

  get 'homes/about' => 'homes#about'
  root :to => "homes#top"

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  def active_for_authentication?
    super && (status == false)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :phone_number, presence: true
  validates :post_code, presence: true
  validates :address, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items

  enum status: {
    入金待ち: 0,
    入金確認: 1,
    製作中: 2,
    発送準備中: 3,
    発送済み: 4
  }

enum payment_method: {クレジットカード: 0, 銀行振込: 1 }

  after_update do
    if self.status == "入金確認"
       self.order_items.each {|order_item|
       order_item.update(production_status: "製作待ち")}
    end
  end

  def cart_items_price
   (item.price*1.1) * quantity
  end

end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admins_customer_path(@customer)
    else
      redirect_to edit_admins_customer_path(@customer)
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :post_code, :address, :phone_number, :status)
  end
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def index
  end

  def show
    @order = Order.find(params[:id])
    @orders = @order.order_items
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    redirect_to admins_order_path(order)
  end

  private

  def order_params
     params.require(:order).permit(:address, :payment_method, :postage, :total_payment, :status)
  end

end

app/controllers/customers/addresses_controller.rb
class Customers::AddressesController < ApplicationController
  before_action :authenticate_customer!

def index
    @addresses = Address.all
    @address = Address.new
end

def show

end

def create
  @address = Address.new(address_params)
  @address.customer_id = current_customer.id
  if @address.save
  redirect_to addresses_path
  else
  @address_new = Address.new
  @addresses = current_customer.addresses
  render :index
  end
end

def edit
  @address = Address.find(params[:id])

end

def update
  address = Address.find(params[:id])
  address.update(address_params)
  redirect_to addresses_path
end

   def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to addresses_path , notice: "Address was successfully destroyed."
   end

private

    def address_params
      params.require(:address).permit(:name, :postal_code, :address)
    end

end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController

    before_action :authenticate_customer!, except: [:show]

  def create
    @cart_item = current_customer.cart_items.new(cart_item_params)
    @cart_items = current_customer.cart_items.all
    if
     @cart_item.quantity == nil
     @genres = Genre.all
     @item = Item.find(cart_item_params[:item_id])
     flash[:notice] = '個数を選択してください'
     render "customers/items/show"
    else
      @cart_items.each do |cart_item|
        if cart_item.item_id == @cart_item.item_id
          new_quantity = cart_item.quantity + @cart_item.quantity
          cart_item.update_attribute(:quantity, new_quantity)
          @cart_item.delete
        end
      end
      @cart_item.save
      redirect_to cart_items_path
    end
  end

  def index
    @cart_items = current_customer.cart_items
  end

  def update
    cart_item = CartItem.find(params[:id])
    cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end

  def destroy_all
    current_customer.cart_items.destroy_all
    redirect_to cart_items_path
  end

  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    redirect_to cart_items_path
  end

private

def cart_item_params
  params.require(:cart_item).permit(:item_id, :quantity, :customer_id)
end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  before_action :authenticate_customer!

  def show

  end

  def edit

  end

  def update
    if current_customer.update(customer_params)
      redirect_to customers_path
    else
      render "edit"
    end
  end

  def withdraw_confirm

  end




  def withdraw_confirm

  end



  def withdraw
    #statusのみをtrueにアップデート
    current_customer.update(status: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :post_code, :address, :phone_number, :email,)

  end

end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController

    before_action :authenticate_customer!,except: [:index,:show]

def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @genres = Genre.all
end

def index
    @items = Item.all
    @item_page = Item.page(params[:page]).reverse_order
    @genres = Genre.all
end

def genreitem
    @genre = Genre.find(params[:id])
    @items = @genre.items
    @genres = Genre.all
    @item_page = Item.page(params[:page]).reverse_order
end

end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController



  def index
    @orders = Order.all
  end

  def new
    @addresses = current_customer.addresses
    @address = Address.new
    @order = Order.new
  end

  def create
    @cart_items = current_customer.cart_items.all
    @order = current_customer.orders.new(order_params)

    if @order.save
      @cart_items.each do |cart_item|
        order_item = OrderItem.new
        order_item.item_id = cart_item.item_id
        order_item.order_id = @order.id
        order_item.quantity = cart_item.quantity
        order_item.save
      end
      redirect_to complete_orders_path
      @cart_items.destroy_all
    else
      @order = Order.new(order_params)
      @addresses = current_customer.addresses
      @address = Address.new
      render :new
    end
  end

   def confirm

    @cart_items = current_customer.cart_items.all
    @order = Order.new(order_params)
    @address = current_customer.addresses.first
    @address = Address.new
    if params[:order][:select] == "1"
      @order.name = current_customer.first_name + current_customer.last_name
      @order.address = current_customer.address
      @order.postal_code = current_customer.post_code
    elsif params[:order][:select] == "2"
      @id =  params[:order][:address_id]
      @order_address = Address.find(@id)
      @order.name = @order_address.name
      @order.address = @order_address.address
      @order.postal_code = @order_address.postal_code
    else
      @order.name = params[:order][:name]
      @order.address = params[:order][:address]
      @order.postal_code = params[:order][:postal_code]
    end

    @sum = @cart_items.inject(0) { |sum, item| sum + item.cart_items_price }
    @total = @cart_items.inject(0) { |sum, item| sum + item.cart_items_price }
    @total += @order.postage

   end

  def show
    @order = Order.find(params[:id])
    @orders = @order.order_items
    @sum = @order.total_payment - @order.postage
  end

  def index
    @orders = Order.all

  end

  private

  def order_params
   params.require(:order).permit(:name, :address, :postal_code, :total_payment, :payment_method)
  end

end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  before_action :reject_customer, only: [:create]

  protected

    def reject_customer
      @customer = Customer.find_by(email: params[:customer][:email])
    #ログイン時に入力されたemailが存在するか探す。
      if @customer
        if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
      #入力されたパスワードが正しいこと 且つ　active_for_authentication?メソッドがfalseであるかどうか。
          flash[:alert] = "このアカウントは退会済みです。"
          redirect_to new_customer_session_path
        end
      else
        flash[:alert] = "必須項目を入力してください"
      end
    end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  
  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    if @customer.update(customer_params)
      redirect_to customers_path
    else
      render :edit
    end
  end
  
  def withdraw_confirm
  end
  
  def withdraw
    
  end
  
  private

  def customer_params
    params.require(user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :post_code, :phone_number, :email,)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/views/customers/orders/_content_order.html.erb
<thead style="background-image: linear-gradient(-45deg, #C6E6FB 15%, #fff 15%, #fff 25%, #C6E6FB 25%, #C6E6FB 65%, #fff 65%, #fff 75%, #C6E6FB 75%, #C6E6FB">
  <tr>
    <th>商品名</th>
    <th>単価（税込）</th>
    <th>数量</th>
    <th>小計</th>
  </tr>
</thead>
<% cart_items.each do |cart_item| %>
  <tbody>
    <tr>
      <td><%= cart_item.item.item %></td>
      <% item_price= cart_item.item.price*1.1 %>
      <td><%= item_price.round.to_s(:delimited)%></td>
      <td><%= cart_item.quantity.round %></td>
      <td><%= cart_item.cart_items_price.round.to_s(:delimited) %></td>
    </tr>
  </tbody>
<% end %>

app/views/customers/orders/_form.html.erb
<%= form_with model:address, url:'/addresses', local:true do |f| %>
　　　<div class="form-group row">
　　　  <label>郵便番号（ハイフンなし）</label>
　　　  <%= f.text_field :postal_code, placeholder: "0000000", class:"form-control w-25 " %>
　　　</div>
　　　<div class="form-group row">
　　　  <label>住所</label>
　　　  <%= f.text_field :address, placeholder: "東京都渋谷区代々木神薗町0-0", class:"form-control w-50 " %>
　　　</div>
　　　<div class="form-group row">
　　　  <label>宛名</label>
　　　  <%= f.text_field :name, placeholder: "令和道子", class:"form-control w-25 " %>
　　　</div>
　　　<div class="form-group-row">
　　　  <%= f.submit '新規登録', class: "btn btn-success" %>
　　　</div>
　　　<% end %>

app/views/customers/orders/complete.html.erb
<h1 class= "text-center m-3">ご注文ありがとうございました！！</h1>
<%= image_tag '5019783_s.jpg', :alt => 'お礼', class: "rounded mx-auto d-block" %>

app/views/customers/orders/confirm.html.erb
<div class= "container ">
  <div class= "row py-3">
    <h2 class= "col-3 text-center design">注文情報確認</h2>
  </div>
</div>

<div class= "container">
  <div class= "row">
    <div class= "d-flex">
      <table class="h-25 table table-bordered">
        <%= render 'customers/orders/content_order', cart_items: @cart_items %>
      </table>

        <table class="offset-1 table table-bordered">
          <tbody>
            <tr>
              <th style="width: 10%; background-image: linear-gradient(-45deg, #C6E6FB 15%, #fff 15%, #fff 25%, #C6E6FB 25%, #C6E6FB 65%, #fff 65%, #fff 75%, #C6E6FB 75%, #C6E6FB">送料</th>
              <td style="width: 40%"><%= @order.postage.round.to_s(:delimited) %></td>
            </tr>
            <tr>
              <th style="width: 10%; background-image: linear-gradient(-45deg, #C6E6FB 15%, #fff 15%, #fff 25%, #C6E6FB 25%, #C6E6FB 65%, #fff 65%, #fff 75%, #C6E6FB 75%, #C6E6FB">商品合計</th>
              <td style="width: 40%"><%= @sum.round.to_s(:delimited) %></td>
            </tr>
            <tr>
              <th style="width: 10%; background-image: linear-gradient(-45deg, #C6E6FB 15%, #fff 15%, #fff 25%, #C6E6FB 25%, #C6E6FB 65%, #fff 65%, #fff 75%, #C6E6FB 75%, #C6E6FB">請求金額</th>
              <td style="width: 40%"><%= @total.round.to_s(:delimited) %></td>
            </tr>
          </tbody>
        </table>
    </div>
  </div>
</div>

<div class= "container ">
  <div class= "row py-3">
    <div class= " p-3 mb-2">

      <h6 class= "col-2" style= " color: #364e96; padding: 0.5em 0; border-top: solid 3px #364e96; border-bottom: solid 3px #364e96;">支払方法</h6>
      <%= @order.payment_method %>

      <h6 class= "col-2 mt-4" style= "color: #364e96; padding: 0.5em 0; border-top: solid 3px #364e96; border-bottom: solid 3px #364e96;">お届け先</h6>
      <%= @order.postal_code %>
      <%= @order.address %><br/>
      <%= @order.name %>

      <%= form_with model: @order, url: orders_path, method: :post, local: true, class: "text-center m-3" do |f| %>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :postal_code %>
        <%= f.hidden_field :address %>
        <%= f.hidden_field :total_payment, value: @total %>
        <%= f.hidden_field :payment_method, value: @order.payment_method %>
        <%= f.submit "注文を確定する", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/customers/orders/index.html.erb
<div class= "container ">
  <div class= "row py-3">
    <h5 class= "col-3 text-center design">注文履歴一覧</h5>
  </div>
</div>

<div class= "container">
  <div class= "row">
    <p class="font-weight-bold">注文情報</p>
    <table class="table table-bordered">
      <thead style="color: #FFF; font-weight: bold; background:#00BCD4;">
        <tr>
          <th>注文日</th>
          <th>配送先</th>
          <th>注文商品</th>
          <th>支払金額</th>
          <th>注文詳細</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <td><%= order.updated_at.strftime('%Y/%m/%d') %></td>
          <td>
            <%= order.address %><br />
            <%= order.name %>
          </td>
          <td>
            <% order.order_items.each do |order_items| %>
              <%= order_items.item.item %><br />
            <% end %>
          </td>
          <td><%= order.total_payment.round.to_s(:delimited) %></td>
          <td><%= link_to "表示する", order_path(order), class: "btn btn-success" %></td>
        </tr>
        <% end %>
      </tbody>
    </div>
  </div>

app/views/customers/orders/new.html.erb
<div class="container">
  <div class="row py-3">
    <div class="offset-1">
      <%= flash[:order_new] %>
      <h2 class="col-3 text-center design">注文情報入力</h2>
    </div>
  </div>

  <div class="row mt-5">
    <div class="offset-2 col-5">

<!-- 支払先 -->
      <div class="row">
        <strong class="px-3" style= "color: #364e96; padding: 0.5em 0; border-top: solid 3px #364e96; border-bottom: solid 3px #364e96;">支払方法</strong>
      </div>

      <%= form_with model:@order, url: confirm_orders_path, method: :post, local:true do |f| %>
        <div class="form-check mt-3">
          <%= f.radio_button :payment_method, :クレジットカード %>
          <%= label_tag :payment_method, "クレジットカード", {value: :"クレジットカード", style: "display: inline-block;"} %><br>
          <%= f.radio_button :payment_method, :銀行振込 %>
          <%= label_tag :payment_method, "銀行振込", {value: :"銀行振込", style: "display: inline-block;"} %>

        </div>

<!-- 支払先 -->

<!-- お届け先 -->
        <div class="row mt-3">
          <strong class="px-3 " style= "color: #364e96; padding: 0.5em 0; border-top: solid 3px #364e96; border-bottom: solid 3px #364e96;">お届け先</strong>
        </div>

        <div class="form-check mt-3">
          <% address = "〒" + current_customer.post_code + " " + current_customer.address + " " + current_customer.first_name + " "  + current_customer.last_name %>
          <%= f.radio_button :select, 1 %>
          <%= label_tag :select, "ご自身の住所",{value: :my_address, style: "display: inline-block;"} %><br>
          <%= address %><br>
          <%= f.radio_button :select, 2 %>
          登録住所から選択<br>

         <div class="form-group">
           <label class="control-label">
           <%= f.collection_select :address_id, @addresses, :id, :alladress, class:"form-control col-lg-5" %>
           </label>
           </div>
         <!--pronptのデータは送られない為、表示させないよう修正-->
        </div>
        <!-- お届け先 -->


        <!-- 新しいお届け先 -->
      <div class="row mt-5">
        <span class="d-flex">
           <%= f.radio_button :select, 3 %><p>新しいお届け先</p>
        </span>
      </div>


        <div class="form-group row">
          <span class= "offset-1 col-10 p-1"><%= f.label :郵便番号（ハイフンなし） %></span>
          <%= f.text_field :postal_code, placeholder: "郵便番号", class: "form-control offset-1 col-10" %>
        </div>

        <div class="form-group row">
          <span class= "offset-1 col-3 p-2"><%= f.label :住所 %></span>
          <%= f.text_field :address, placeholder: "東京都渋谷区代々木神園町0-0", class: "form-control offset-1 col-10" %>
        </div>

        <div class="form-group row">
          <span class= "offset-1 col-3 p-2"><%= f.label :宛名 %></span>
          <%= f.text_field :name, placeholder:"令和道子", class: "form-control offset-1 col-5" %>
        </div>
<!-- 新しいお届け先 -->

        <div class="row mt-5 offset-4 col-6">
          <%= f.submit '確認画面へ進む', class: "btn btn-primary" %>
        </div>


    </div>
      <% end %>



    </div>


</div>

app/views/customers/orders/order_complete.html.erb
<h1 class= text-center>ご注文ありがとうございました</h1>

app/views/customers/orders/show.html.erb
<div class= "container ">
  <div class= "row py-3">
    <h5 class= "col-3 text-center p-3 mb-2 bg-light text-dark">注文履歴詳細</h5>
  </div>
</div>

<div class= "container">
  <div class= "row">
    <div class= "d-flex">
      <div class= "col">
        <p class="font-weight-bold">注文情報</p>
        <table class="order-table table table-bordered">
          <tbody>
            <tr>
              <th style="width: 30%; background-color: #EEEEEE;">注文日</th>
              <td><%= @order.updated_at.strftime('%Y/%m/%d') %></td>
            </tr>
            <tr>
              <th style="width: 30%; background-color: #EEEEEE;">配送先</th>
              <td>
                <%= @order.address %><br />
                <%= @order.name %>
              </td>
            </tr>
            <tr>
              <th style="width: 30%; background-color: #EEEEEE;">支払い方法</th>
              <td><%= @order.payment_method %></td>
            </tr>
            <tr>
              <th style="width: 30%; background-color: #EEEEEE;">ステータス</th>
              <td><%= @order.status %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class= "col offset-1">
        <p class="font-weight-bold">請求情報</p>
        <table class="order-table table table-bordered">
          <tbody>
            <tr>
              <th style="width: 30%; background-color: #EEEEEE;">商品合計</th>
              <td><%= @sum.round.to_s(:delimited) %></td>
            </tr>
            <tr>
              <th style="width: 30%; background-color: #EEEEEE;">配送料</th>
              <td><%= @order.postage.round.to_s(:delimited) %></td>
            </tr>
            <tr>
              <th style="width: 30%; background-color: #EEEEEE;">ご請求額</th>
              <td class="font-weight-bold"><%= @order.total_payment.round.to_s(:delimited) %></td>
            </tr>
          </tbody>
        </table>
      </div>
  </div>
</div>

<div class= "container">
  <div class= "row">
    <p class="font-weight-bold">注文内容</p>
    <table class="table table-bordered" style="width:1000px;">
      <thead style="background-color: #EEEEEE;">
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
        </tr>
      </thead>
      <% @orders.each do |order| %>
        <tbody>
          <tr>
            <td><%= order.item.item %></td>
            <% item_price= order.item.price*1.1 %>
            <td><%= item_price.round.to_s(:delimited)%></td>
            <td><%= order.quantity.round %></td>
            <td><%= (item_price * order.quantity).round.to_s(:delimited) %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>