config/routes.rb
Rails.application.routes.draw do

  scope module: 'customers' do
    resource :customers, except: :create
    resources :items
    get '/genreitem/:id' => 'items#genreitem', as: 'genreitems'
    resources :orders do
      collection do
        post :confirm
        get :complete

      end
    end
    resources :cart_items do

    collection do
    delete 'destroy_all', to: 'cart_items#destroy_all'
    end

    end

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    get '/customers/withdraw_confirm' => 'customers#withdraw_confirm'
    patch '/customers/withdraw' => 'customers#withdraw'

  end


   devise_for :admins,skip: [:passwords], controllers: {
  sessions: "admins/sessions"
}
    namespace :admins do
    resources :items
    resources :customers
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:index, :update, :show] do
      resources :order_items, only: [:update]
    end
    get '/' => 'homes#top'

  end

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "customers/registrations",
    sessions: 'customers/sessions'
}

  get 'homes/about' => 'homes#about'
  root :to => "homes#top"

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer
  validates :postal_code, presence: true #, format: {with: /^\d{7}$}　# 郵便番号（ハイフンなし7桁）
  validates :name,  presence: true
  validates :address, presence: true
  
  def alladress
    "〒" + postal_code + address + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
 belongs_to :item
 belongs_to :customer

  def cart_items_price
   (item.price*1.1) * quantity
  end

  validates :quantity, inclusion: { in: 1..10 }

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  def active_for_authentication?
    super && (status == false)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :phone_number, presence: true
  validates :post_code, presence: true
  validates :address, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  attachment :image
  has_many :orders
  belongs_to :genre

  validates :item, presence: true
  validates :item_explanation, presence: true
  validates :price, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items

  enum status: {
    入金待ち: 0,
    入金確認: 1,
    製作中: 2,
    発送準備中: 3,
    発送済み: 4
  }

enum payment_method: {クレジットカード: 0, 銀行振込: 1 }

  after_update do
    if self.status == "入金確認"
       self.order_items.each {|order_item|
       order_item.update(production_status: "製作待ち")}
    end
  end

  def cart_items_price
   (item.price*1.1) * quantity
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum production_status: {
    着手不可:0,
    製作待ち:1,
    製作中:2,
    製作完了:3
  }

  after_update do
    order_items = self.order.order_items
    if order_items.any? {|order_item| order_item.production_status == "製作中"} == true #製作ステータスが1つでも製作中なら
      self.order.update(status: "製作中") #注文ステータスを製作中へ変更
    elsif order_items.all? {|order_item| order_item.production_status == "製作完了"} == true #製作ステータスが全て製作完了なら
      self.order.update(status: "発送準備中") #注文ステータスを発送準備中へ変更
    end
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.all
    @item_page = Item.page(params[:page]).reverse_order
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_item_path(@item.id)
    else
      render "edit"
    end
  end

  def new
   @item = Item.new
   @genres = Genre.all
  end

  def create
   @item = Item.new(item_params)
   @item.save
   redirect_to admins_item_path(@item)

  end

  private
  def item_params

    params.require(:item).permit(:genre_id, :item, :image, :item_explanation, :price, :sale_status, :created_at, :updated_at)

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Customer
      root_path
    when Admin
      admins_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :email, :post_code, :address, :phone_number])
  end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController

    before_action :authenticate_customer!,except: [:index,:show]

def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @genres = Genre.all
end

def index
    @items = Item.all
    @item_page = Item.page(params[:page]).reverse_order
    @genres = Genre.all
end

def genreitem
    @genre = Genre.find(params[:id])
    @items = @genre.items
    @genres = Genre.all
    @item_page = Item.page(params[:page]).reverse_order
end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  
  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    if @customer.update(customer_params)
      redirect_to customers_path
    else
      render :edit
    end
  end
  
  def withdraw_confirm
  end
  
  def withdraw
    
  end
  
  private

  def customer_params
    params.require(user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :post_code, :phone_number, :email,)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @items = Item.where(sale_status: "販売中")
    @genres = Genre.all
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/items/edit.html.erb
<div class= "container ">
  <div class= "row py-3">
    <h5 class= "col-3 manage">商品編集</h5>
  </div>
</div>

<% if @item.errors.any? %>
  <h3><%= @item.errors.count %>：件のエラーがあります</h3>
    <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

<div class= "container ">
  <div class= "row py-3">
    <div class= "mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <%= form_with model:@item, url: admins_item_path(@item), local:true do |f| %>

        <div class= "mb-4 form-group">
          <label class= "col-2 p-2">商品画像</label>
          <span><%= f.attachment_field :image, placeholder: "商品画像" %></span>
        </div>

        <div class= "mb-4 d-flex form-group">
          <label class= "col-2 p-2">商品名</label>
          <%= f.text_field :item, autofocus: true, placeholder:"商品名", class: "form-control", style: "color: #364e96; border: solid 3px #364e96; padding: 0.5em; border-radius: 0.5em;"%>
        </div>

        <div class= "mb-4 d-flex form-group">
          <label class= "col-2 p-2">商品説明</label>
          <%= f.text_area :item_explanation, autofocus: true, placeholder:"ここに説明文を記述します", class: "form-control", style: "color: #364e96; border: solid 3px #364e96; padding: 0.5em; border-radius: 0.5em;" %>
        </div>
        <div class= "mb-4 d-flex form-group">
          <label class= "col-2 p-2">ジャンル</label>
           <%= f.collection_select :genre_id, Genre.all, :id, :genre_name, class: "form-control", style: "color: #364e96; border: solid 3px #364e96; padding: 0.5em; border-radius: 0.5em;" %>
        </div>



        <div class= "mb-4 d-flex form-group">
          <label class= "col-2 p-2">税別価格</label>
          <%= f.text_field :price, autofocus: true, placeholder:"選択されていません", class: "form-control col-sm-8", style: "color: #364e96; border: solid 3px #364e96; padding: 0.5em; border-radius: 0.5em;" %>
        </div>

        <div class= "mb-4 d-flex form-group">
          <label class= "col-3 p-2">販売ステータス</label>
         	<%= f.radio_button :sale_status, true %>
          <%= f.label :sale_status, "販売中" %>
          <%= f.radio_button :sale_status, false %>
          <%= f.label :sale_status, "販売停止中" %>
        </div>

      <%= f.submit "変更を保存", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/items/index.html.erb
 <div class= "container">
  <div class= "row px-3">
     <div class= "text-end m-3">
      <%= link_to new_admins_item_path do %>
         <i class="fas fa-plus" style="font-size:3em; color: #444444;"></i>
      <% end %>
    </div>
  </div>
</div>

 <table class='table table-hover table-inverse'>

  <thead>
     <h1 class="col-3 manage">商品一覧</h1>
    <tr style="color:#fff; background:#005ab3;">
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.item, admins_item_path(item.id) %>
        </td>

        <td><%= number_to_currency(item.price) %></td>

         <td><%= item.genre.genre_name %></td>
         <td><% if item.sale_status == true %>

          <h7><strong class='ture' style="color :limegreen;">販売中</strong></h7>
          <% else %>
	  	    <h7><strong class='false' style="color :#d3d3d3;">販売停止中</strong></h7>
	  	    <% end %>
	  	    </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
  </div>

<%= paginate @item_page %>

app/views/admins/items/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3 class= "col-3 manage">商品新規登録</h3>
      <%= form_with model:@item, url:'/admins/items', local:true do |f| %>

      <div>
         <%= f.label :商品画像 %>
         <%= f.attachment_field :image, class: "image", style: "color: #364e96; border: solid 3px #364e96; padding: 0.5em; border-radius: 0.5em;" %>
      </div>
      <div>
        <%= f.label :商品名 %>
        <%= f.text_field :item, class: "form-control item", style: "color: #364e96; border: solid 3px #364e96; padding: 0.5em; border-radius: 0.5em;" %>
      </div>
      <div>
        <%= f.label :商品説明 %>
        <%= f.text_area :item_explanation, class:"form-control item_explanation", style: "color: #364e96; border: solid 3px #364e96; padding: 0.5em; border-radius: 0.5em;" %><br>
      </div>
      <div>
        <%= f.label :ジャンル %>
    　   <%= f.collection_select :genre_id, @genres, :id, :genre_name, include_blank: "-- 選択して下さい --" %>
      </div>
      <div>

      <%= f.label :税抜価格 %>
      <%= f.text_field :price, class: "form-control price", style: "color: #364e96; border: solid 3px #364e96; padding: 0.5em; border-radius: 0.5em;" %>
      </div>
      <div>
        <%= f.label :販売ステータス %>
       	<%= f.radio_button :sale_status, true %>
        <%= f.label :sale_status, "販売中" %>
        <%= f.radio_button :sale_status, false %>
        <%= f.label :sale_status, "販売停止中" %>
      </div>

      <div class="form-group">
        <%= f.submit "新規登録", class:"btn btn-secondary" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/admins/items/show.html.erb
<!--商品詳細ページ{Tsuyoshi}-->

<div class="container my-5">
  <div class="row">
    <h2 class="col-3 manage">商品詳細</h2>
  </div>

 <!--商品投稿ページから情報を取得する為、記述。(商品投稿が完成次第有効にする){Tsuyoshi}-->

  <div class="row mt-3">
   <div class="offset-sm-1 col-sm-3">
      <%= attachment_image_tag @item, :image, :fill, 200, 200, format: "jpeg", fallback: 'noimage.jpg', size: '200x200' %>
    </div>

    <div class="col-sm-4">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>商品名</td>
            <td><%= @item.item %></td>
          </tr>

          <tr>
            <td>商品説明</td>
            <td><%= @item.item_explanation %></td>
          </tr>

          <tr>
            <td>ジャンル</td>
            <td><%= @item.genre.genre_name %></td>
          </tr>

          <tr>
            <td>税込価格(税抜価格)</td>
            <td>
              <%=(@item.price * 1.1).floor %>(<%= @item.price %>)円
            </td>
          </tr>

          <tr>
            <td>販売ステータス</td>
              <td>
              <% if @item.sale_status == false %>
               <h7><strong class='false' style="color :#d3d3d3;">販売停止中</strong></h7>
              <% else %>
	  	         <h7><strong class='ture' style="color :limegreen;">販売中</strong></h7>
	  	        <% end %>
              </td>
          </tr>
        </tbody>

      </table>
    </div>
  </div>

  <div class="row">
    <div class="offset-sm-9 col-sm-2">
      <%= link_to "編集する", edit_admins_item_path(@item), class: "btn btn-primary" %>
    </div>
  </div>
</div>
<!--商品詳細ページ{Tsuyoshi}-->