config/routes.rb
Rails.application.routes.draw do

  scope module: 'customers' do
    resource :customers, except: :create
    resources :items
    get '/genreitem/:id' => 'items#genreitem', as: 'genreitems'
    resources :orders do
      collection do
        post :confirm
        get :complete

      end
    end
    resources :cart_items do

    collection do
    delete 'destroy_all', to: 'cart_items#destroy_all'
    end

    end

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    get '/customers/withdraw_confirm' => 'customers#withdraw_confirm'
    patch '/customers/withdraw' => 'customers#withdraw'

  end


   devise_for :admins,skip: [:passwords], controllers: {
  sessions: "admins/sessions"
}
    namespace :admins do
    resources :items
    resources :customers
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:index, :update, :show] do
      resources :order_items, only: [:update]
    end
    get '/' => 'homes#top'

  end

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "customers/registrations",
    sessions: 'customers/sessions'
}

  get 'homes/about' => 'homes#about'
  root :to => "homes#top"

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer
  validates :postal_code, presence: true #, format: {with: /^\d{7}$}　# 郵便番号（ハイフンなし7桁）
  validates :name,  presence: true
  validates :address, presence: true
  
  def alladress
    "〒" + postal_code + address + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
 belongs_to :item
 belongs_to :customer

  def cart_items_price
   (item.price*1.1) * quantity
  end

  validates :quantity, inclusion: { in: 1..10 }

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  def active_for_authentication?
    super && (status == false)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :phone_number, presence: true
  validates :post_code, presence: true
  validates :address, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  attachment :image
  has_many :orders
  belongs_to :genre

  validates :item, presence: true
  validates :item_explanation, presence: true
  validates :price, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items

  enum status: {
    入金待ち: 0,
    入金確認: 1,
    製作中: 2,
    発送準備中: 3,
    発送済み: 4
  }

enum payment_method: {クレジットカード: 0, 銀行振込: 1 }

  after_update do
    if self.status == "入金確認"
       self.order_items.each {|order_item|
       order_item.update(production_status: "製作待ち")}
    end
  end

  def cart_items_price
   (item.price*1.1) * quantity
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum production_status: {
    着手不可:0,
    製作待ち:1,
    製作中:2,
    製作完了:3
  }

  after_update do
    order_items = self.order.order_items
    if order_items.any? {|order_item| order_item.production_status == "製作中"} == true #製作ステータスが1つでも製作中なら
      self.order.update(status: "製作中") #注文ステータスを製作中へ変更
    elsif order_items.all? {|order_item| order_item.production_status == "製作完了"} == true #製作ステータスが全て製作完了なら
      self.order.update(status: "発送準備中") #注文ステータスを発送準備中へ変更
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Customer
      root_path
    when Admin
      admins_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :email, :post_code, :address, :phone_number])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  
  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    if @customer.update(customer_params)
      redirect_to customers_path
    else
      render :edit
    end
  end
  
  def withdraw_confirm
  end
  
  def withdraw
    
  end
  
  private

  def customer_params
    params.require(user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :post_code, :phone_number, :email,)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @items = Item.where(sale_status: "販売中")
    @genres = Genre.all
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Yomogi&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@300&display=swap" rel="stylesheet">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="Logo navbar-brand p-3" href="/">
            <%= link_to root_path, class:"header-title" do %>
             <div>ながのCake</div>
            <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav lists-right">
              <% if customer_signed_in? %>

                <li class= "nav-item">
                 <button class="btn btn-default"> <%= link_to "マイページ", customers_path, class: "link" %></button>
                </li>

                <li class= "nav-item">
                  <button class="btn btn-default"><%= link_to "商品一覧", items_path, class: "link" %></button>
                </li>

                <li class= "nav-item">
                  <button class="btn btn-default"><%= link_to "カート", cart_items_path, class: "link" %></button>
                </li>

                <li class="nav-item">
                  <button class="btn btn-default"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "link" %></button>
                </li>

              <% elsif admin_signed_in? %>
                <li class= items>
                  <button class="btn btn-default"><%= link_to '商品一覧', admins_items_path, class: "link" %></button>
                </li>

                <li class= customers>
                  <button class="btn btn-default"><%= link_to '会員一覧', admins_customers_path, class: "link" %></button>
                </li>

                <li class=orders>
                  <button class="btn btn-default"><%= link_to '注文履歴一覧', admins_path, class: "link" %></button>
                </li>

                <li class=genres>
                  <button class="btn btn-default"><%= link_to 'ジャンル一覧', admins_genres_path, class: "link" %></button>
                </li>

                <li class=logout>
                  <button class="btn btn-default"><%= link_to "ログアウト",destroy_admin_session_path, method: :delete, class: "link" %></button>
                </li>

              <% else %>
                <li class= "nav-item">
                  <button class="btn btn-default"><%= link_to "About", homes_about_path, class: "link" %></button>
                </li>

                 <li class= "nav-item">
                   <button class="btn btn-default"><%= link_to "商品一覧", items_path, class: "link" %></button>
                </li>

                <li class= "nav-item">
                  <button class="btn btn-default"><%= link_to "新規登録", new_customer_registration_path, class: "link" %></button>
                </li>

                <li class= "nav-item">
                 <button class="btn btn-default"><%= link_to "ログイン", new_customer_session_path, class: "link" %></button>
                </li>
              <% end %>
              </ul>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto" style="font-family: 'Kiwi Maru', serif;">
    <%= notice %>
    <%= yield %>
    </main>

  </body>

  </html>