config/routes.rb
Rails.application.routes.draw do

  scope module: 'customers' do
    resource :customers, except: :create
    resources :items
    get '/genreitem/:id' => 'items#genreitem', as: 'genreitems'
    resources :orders do
      collection do
        post :confirm
        get :complete

      end
    end
    resources :cart_items do

    collection do
    delete 'destroy_all', to: 'cart_items#destroy_all'
    end

    end

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    get '/customers/withdraw_confirm' => 'customers#withdraw_confirm'
    patch '/customers/withdraw' => 'customers#withdraw'

  end


   devise_for :admins,skip: [:passwords], controllers: {
  sessions: "admins/sessions"
}
    namespace :admins do
    resources :items
    resources :customers
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:index, :update, :show] do
      resources :order_items, only: [:update]
    end
    get '/' => 'homes#top'

  end

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "customers/registrations",
    sessions: 'customers/sessions'
}

  get 'homes/about' => 'homes#about'
  root :to => "homes#top"

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items

  enum status: {
    入金待ち: 0,
    入金確認: 1,
    製作中: 2,
    発送準備中: 3,
    発送済み: 4
  }

enum payment_method: {クレジットカード: 0, 銀行振込: 1 }

  after_update do
    if self.status == "入金確認"
       self.order_items.each {|order_item|
       order_item.update(production_status: "製作待ち")}
    end
  end

  def cart_items_price
   (item.price*1.1) * quantity
  end

end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def index
  end

  def show
    @order = Order.find(params[:id])
    @orders = @order.order_items
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    redirect_to admins_order_path(order)
  end

  private

  def order_params
     params.require(:order).permit(:address, :payment_method, :postage, :total_payment, :status)
  end

end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController



  def index
    @orders = Order.all
  end

  def new
    @addresses = current_customer.addresses
    @address = Address.new
    @order = Order.new
  end

  def create
    @cart_items = current_customer.cart_items.all
    @order = current_customer.orders.new(order_params)

    if @order.save
      @cart_items.each do |cart_item|
        order_item = OrderItem.new
        order_item.item_id = cart_item.item_id
        order_item.order_id = @order.id
        order_item.quantity = cart_item.quantity
        order_item.save
      end
      redirect_to complete_orders_path
      @cart_items.destroy_all
    else
      @order = Order.new(order_params)
      @addresses = current_customer.addresses
      @address = Address.new
      render :new
    end
  end

   def confirm

    @cart_items = current_customer.cart_items.all
    @order = Order.new(order_params)
    @address = current_customer.addresses.first
    @address = Address.new
    if params[:order][:select] == "1"
      @order.name = current_customer.first_name + current_customer.last_name
      @order.address = current_customer.address
      @order.postal_code = current_customer.post_code
    elsif params[:order][:select] == "2"
      @id =  params[:order][:address_id]
      @order_address = Address.find(@id)
      @order.name = @order_address.name
      @order.address = @order_address.address
      @order.postal_code = @order_address.postal_code
    else
      @order.name = params[:order][:name]
      @order.address = params[:order][:address]
      @order.postal_code = params[:order][:postal_code]
    end

    @sum = @cart_items.inject(0) { |sum, item| sum + item.cart_items_price }
    @total = @cart_items.inject(0) { |sum, item| sum + item.cart_items_price }
    @total += @order.postage

   end

  def show
    @order = Order.find(params[:id])
    @orders = @order.order_items
    @sum = @order.total_payment - @order.postage
  end

  def index
    @orders = Order.all

  end

  private

  def order_params
   params.require(:order).permit(:name, :address, :postal_code, :total_payment, :payment_method)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/orders/show.html.erb
<div class= "container ">
  <div class= "row py-3">
    <h5 class= "col-3 manage">注文履歴詳細</h5>
  </div>
</div>

  <div class="row px-3">
    <div class="col-5">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>購入者</td>
            <td>
              <%= link_to admins_customer_path(@order.customer) do %>
              <%= @order.name %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td>注文日</td>
            <td><%= @order.updated_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
            <td>配送先</td>
            <td><%= "〒" + @order.postal_code + "  " + @order.address + "  " + @order.name %></td>
          </tr>
          <tr>
            <td>支払方法</td>
            <td><%= @order.payment_method %></td>
          </tr>
          <tr>
            <td>注文ステータス</td>
            <td><%= form_with model:@order, url: admins_order_path(@order), local: true do |f| %>
                <%= f.select :status, [["入金待ち", "入金待ち"], ["入金確認","入金確認"],["製作中","製作中"],["発送準備中","発送準備中"],["発送済み","発送済み"]], class: "form-control" %>
                <%= f.submit "更新", class: "btn btn-primary btn-sm" %>
                <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row px-3">
    <div class="col-7">
      <table class="table table-hover">
        <thead>
          <tr style="color:#fff; background:#005ab3;" >
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th colspan="1"></th>
          </tr>
        </thead>

        <% @orders.each do |order_item| %>
          <tbody>
            <tr>
              <td><%= order_item.item.item %></td>
              <td><%= (order_item.item.price * 1.1).round.to_s(:delimited) %></td>
              <td><%= order_item.quantity %></td>
              <td><%= (order_item.item.price * order_item.quantity * 1.1).round.to_s(:delimited) %></td>
              <td>
                <%= form_with model: order_item, url: admins_order_order_item_path(@order.id, order_item.id), method: :patch, local:true do |f| %>
                  <%= f.select :production_status, [['着手不可', '着手不可'], ['製作待ち','製作待ち'], ['製作中','製作中'], ['製作完了','製作完了']] %>
                  <%= f.submit "更新", class: "btn btn-primary btn-sm ml-3" %>
                <% end %>

                </td>
            </tr>
          </tbody>
      <% end %>
      </table>
    </div>

    <div class="col-sm-3 d-flex">
      <table class="table table-borderless align-self-end">
        <tbody>
          <tr style="border-bottom:2px solid #005ab3;">
            <td>商品合計</td>
            <td><%= (@order.total_payment -= @order.postage).round.to_s(:delimited) %></td>
          </tr>
          <tr style="border-bottom:2px solid #005ab3;">
            <td>送料</td>
            <td><%= @order.postage %></td>
          </tr>
          <tr>
            <td>請求合計金額</td>
            <td><%= (@order.total_payment + @order.postage).round.to_s(:delimited)  %></td>
          </tr>
        </tbody>
      </table>

    </div>
  </div>
</div>